#!/bin/bash


usage() {
  echo "Usage: $(basename $0) [-igc] cluster_domain/cip_id" >&2
  exit 2
}

while getopts "chig" opt; do
  case "$opt" in
    h)
      usage
      ;;
    g)
      group_cleanup=1
      ;;
    i)
      image_cleanup=1
      ;;
    c)
      cloudip_cleanup=1
  esac
done

shift $((OPTIND-1))

[[ "$1" = "--" ]] && shift

[[ $# -eq 1 ]] || usage

if [[ -z "${target}" ]]; then
  echo "Name filter guard missing in script. Aborting" >&2
  exit 2
fi

source $(dirname $0)/build-common

cloudip_id=$(echo $1 | grep -o 'cip-[[:alnum:]]\{5\}')
if [[ -z "${cloudip_id}" ]]; then
  echo "Unable to detect cloud ip id in $1" >&2
  exit 2
fi

echo "Cleaning up load balancer and servers"
map_id=$(brightbox -s cloudip ${cloudip_id} 2>/dev/null | cut -f4)
case "${map_id}" in
  lba-*)
    server_list=( $(brightbox -s lbs ${map_id} 2>/dev/null | cut -f5 | sed 's/,/ /g') )
    object_list=( ${map_id} "${server_list[@]}" )
    ;;
  srv-*)
    server_list=( ${map_id} )
    object_list=( ${map_id} )
    ;;
esac

if [[ "${group_cleanup}" ]]; then
  echo "Group option chosen. Cleaning up groups"
  group_list=( $(brightbox -s server show ${server_list} 2>/dev/null | sed -n '/server_groups\?\t/ {
   s///
   s/,//g
   p
   }') )
  object_list=( "${object_list[@]}" "${group_list[@]}" )
  for ((i=0; i<${#group_list[*]}; i++)); do
    firewall_policy=$(brightbox -s group show ${group_list[i]} 2>/dev/null | sed -n '/firewall_policy\t/s///p')
    if [[ "${firewall_policy}" ]]; then
      object_list=( "${object_list[@]}" ${firewall_policy} ) 
    fi
  done
fi

if [[ "${image_cleanup}" ]]; then
  echo "Image option chosen. Cleaning up images"
  object_list=( "${object_list[@]}" $(brightbox -s server show ${server_list} 2>/dev/null | sed -n '/image\t/s///p') )
fi
  
echo "Cloud IP is ${cloudip_id}"
for ((i=0; i<${#object_list[*]}; i++)); do
  case "${object_list[i]}" in
    lba*)
      sub_command=lbs
      ;;
    srv*)
      sub_command=server
      ;;
    grp*)
      sub_command=group
      ;;
    fwp*)
      sub_command=firewall-policies
      ;;
    img*)
      sub_command=images
      ;;
  esac
  if brightbox -s ${sub_command} show ${object_list[i]} 2> /dev/null |
    grep -q "name.*${target}"; then
    while ! brightbox "${sub_command}" destroy "${object_list[i]}"; do
      echo "${sub_command} destroy command failed - waiting 20 secs"
      sleep 20
      echo "Retry"
    done
    echo "Destroyed ${object_list[i]}"
  else
    echo "Skipping non-${target} object ${object_list[i]}"
  fi
done

[[ "${cloudip_cleanup}" ]] && brightbox cloudip destroy "${cloudip_id}"
exit 0
