#!/bin/bash

# Function library for Flynn build scripts

source $(dirname $0)/../lib/common

# The Userdata script used to create a Flynn server
userscript() {
cat <<"SCRIPT"
#!/bin/bash

set -e 
service cron stop

apt_options="--option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet"
flynn_script="https://dl.flynn.io/install-flynn"

apt-get ${apt_options} update
DEBIAN_FRONTEND=noninteractive apt-get ${apt_options} install --install-recommends language-pack-en linux-generic-lts-vivid
DEBIAN_FRONTEND=noninteractive apt-get ${apt_options} autoremove
DEBIAN_FRONTEND=noninteractive apt-get ${apt_options} dist-upgrade
curl -fsSL -o /tmp/install-flynn "${flynn_script}"
source /tmp/install-flynn
shutdown -P +1&
SCRIPT
}

